use anyhow::Result;
use colored::Colorize;
use cooper_codegen::analyzer::RouteInfo;
use std::fs;

pub async fn client(lang: &str) -> Result<()> {
    let project_root = std::env::current_dir()?;
    let analysis = cooper_codegen::analyzer::analyze(&project_root)?;

    eprintln!(
        "  {} Generating {} client from {} routes...",
        "→".cyan(),
        lang.bold(),
        analysis.routes.len()
    );

    fs::create_dir_all(".cooper/gen")?;

    match lang {
        "typescript" | "ts" => {
            let code = generate_typescript_client(&analysis.routes);
            fs::write(".cooper/gen/client.ts", &code)?;
            eprintln!("  {} Generated → .cooper/gen/client.ts", "✓".green());
        }
        "python" | "py" => {
            let code = generate_python_client(&analysis.routes);
            fs::write(".cooper/gen/client.py", &code)?;
            eprintln!("  {} Generated → .cooper/gen/client.py", "✓".green());
        }
        "rust" | "rs" => {
            let code = generate_rust_client(&analysis.routes);
            fs::write(".cooper/gen/client.rs", &code)?;
            eprintln!("  {} Generated → .cooper/gen/client.rs", "✓".green());
        }
        _ => {
            return Err(anyhow::anyhow!(
                "Unsupported language: {}. Use typescript, python, or rust.",
                lang
            ));
        }
    }

    Ok(())
}

pub async fn openapi() -> Result<()> {
    let project_root = std::env::current_dir()?;
    let analysis = cooper_codegen::analyzer::analyze(&project_root)?;

    let spec = cooper_codegen::openapi::generate(&analysis, "Cooper API", "0.1.0");
    let json = serde_json::to_string_pretty(&spec)?;

    fs::create_dir_all(".cooper/gen")?;
    fs::write(".cooper/gen/openapi.json", &json)?;

    eprintln!(
        "  {} Generated OpenAPI 3.1 spec → .cooper/gen/openapi.json",
        "✓".green()
    );
    Ok(())
}

pub async fn postman() -> Result<()> {
    let project_root = std::env::current_dir()?;
    let analysis = cooper_codegen::analyzer::analyze(&project_root)?;

    let collection = generate_postman_collection(&analysis.routes);
    let json = serde_json::to_string_pretty(&collection)?;

    fs::create_dir_all(".cooper/gen")?;
    fs::write(".cooper/gen/postman.json", &json)?;

    eprintln!(
        "  {} Generated Postman collection → .cooper/gen/postman.json",
        "✓".green()
    );
    Ok(())
}

fn generate_typescript_client(routes: &[RouteInfo]) -> String {
    let mut code = String::from(
        r#"// Auto-generated by Cooper — do not edit manually.
// Regenerate with: cooper gen client --lang typescript

export interface CooperClientConfig {
  baseUrl: string;
  token?: string;
  headers?: Record<string, string>;
}

class CooperClientBase {
  constructor(private config: CooperClientConfig) {}

  protected async request<T>(
    method: string,
    path: string,
    opts?: { body?: any; params?: Record<string, string> }
  ): Promise<T> {
    let url = this.config.baseUrl + path;
    if (opts?.params) {
      for (const [key, value] of Object.entries(opts.params)) {
        url = url.replace(`:${key}`, encodeURIComponent(value));
      }
    }

    const headers: Record<string, string> = {
      "Content-Type": "application/json",
      ...this.config.headers,
    };
    if (this.config.token) {
      headers["Authorization"] = `Bearer ${this.config.token}`;
    }

    const res = await fetch(url, {
      method,
      headers,
      body: opts?.body ? JSON.stringify(opts.body) : undefined,
    });

    if (!res.ok) {
      const err = await res.json().catch(() => ({
        error: { code: "UNKNOWN", message: res.statusText },
      }));
      throw err;
    }

    return res.json();
  }
}

"#,
    );

    code.push_str("export class CooperClient extends CooperClientBase {\n");

    for route in routes {
        let fn_name = &route.export_name;
        let method = route.method.to_uppercase();
        let path = &route.path;

        let params: Vec<&str> = path
            .split('/')
            .filter_map(|s| s.strip_prefix(':'))
            .collect();
        let has_body = matches!(method.as_str(), "POST" | "PUT" | "PATCH");

        let mut args = Vec::new();
        for param in &params {
            args.push(format!("{param}: string"));
        }
        if has_body {
            args.push("body: any".to_string());
        }
        let args_str = args.join(", ");

        let mut opts_parts = Vec::new();
        if !params.is_empty() {
            let param_map: Vec<String> = params.iter().map(|p| p.to_string()).collect();
            opts_parts.push(format!("params: {{ {} }}", param_map.join(", ")));
        }
        if has_body {
            opts_parts.push("body".to_string());
        }
        let opts_str = if opts_parts.is_empty() {
            String::new()
        } else {
            format!(", {{ {} }}", opts_parts.join(", "))
        };

        code.push_str(&format!(
            "  async {fn_name}({args_str}): Promise<any> {{\n    return this.request(\"{method}\", \"{path}\"{opts_str});\n  }}\n\n"
        ));
    }

    code.push_str("}\n");
    code
}

fn generate_python_client(routes: &[RouteInfo]) -> String {
    let mut code = String::from(
        r#"# Auto-generated by Cooper — do not edit manually.
# Regenerate with: cooper gen client --lang python

import httpx
from typing import Any, Optional


class CooperClient:
    def __init__(self, base_url: str, token: Optional[str] = None):
        self.base_url = base_url.rstrip("/")
        self.token = token
        self._client = httpx.Client()

    def _headers(self) -> dict:
        headers = {"Content-Type": "application/json"}
        if self.token:
            headers["Authorization"] = f"Bearer {self.token}"
        return headers

    def _request(self, method: str, path: str, **kwargs) -> Any:
        url = self.base_url + path
        params = kwargs.pop("path_params", {})
        for key, value in params.items():
            url = url.replace(f":{key}", str(value))
        resp = self._client.request(method, url, headers=self._headers(), **kwargs)
        resp.raise_for_status()
        return resp.json()

"#,
    );

    for route in routes {
        let fn_name = to_snake_case(&route.export_name);
        let method = route.method.to_uppercase();
        let path = &route.path;

        let params: Vec<&str> = path
            .split('/')
            .filter_map(|s| s.strip_prefix(':'))
            .collect();
        let has_body = matches!(method.as_str(), "POST" | "PUT" | "PATCH");

        let mut args = vec!["self".to_string()];
        for param in &params {
            args.push(format!("{param}: str"));
        }
        if has_body {
            args.push("body: dict = None".to_string());
        }
        let args_str = args.join(", ");

        let mut call_args = Vec::new();
        if !params.is_empty() {
            let param_map: Vec<String> =
                params.iter().map(|p| format!("\"{p}\": {p}")).collect();
            call_args.push(format!("path_params={{{}}}", param_map.join(", ")));
        }
        if has_body {
            call_args.push("json=body".to_string());
        }
        let call_str = if call_args.is_empty() {
            String::new()
        } else {
            format!(", {}", call_args.join(", "))
        };

        code.push_str(&format!(
            "    def {fn_name}({args_str}) -> Any:\n        return self._request(\"{method}\", \"{path}\"{call_str})\n\n"
        ));
    }

    code
}

fn generate_rust_client(routes: &[RouteInfo]) -> String {
    let mut code = String::from(
        r#"// Auto-generated by Cooper — do not edit manually.
// Regenerate with: cooper gen client --lang rust

use reqwest::Client;
use serde_json::Value;
use anyhow::Result;

pub struct CooperClient {
    base_url: String,
    token: Option<String>,
    client: Client,
}

impl CooperClient {
    pub fn new(base_url: &str) -> Self {
        Self {
            base_url: base_url.trim_end_matches('/').to_string(),
            token: None,
            client: Client::new(),
        }
    }

    pub fn with_token(mut self, token: &str) -> Self {
        self.token = Some(token.to_string());
        self
    }

    async fn request(&self, method: &str, path: &str, body: Option<&Value>) -> Result<Value> {
        let url = format!("{}{}", self.base_url, path);
        let mut req = match method {
            "GET" => self.client.get(&url),
            "POST" => self.client.post(&url),
            "PUT" => self.client.put(&url),
            "PATCH" => self.client.patch(&url),
            "DELETE" => self.client.delete(&url),
            _ => self.client.get(&url),
        };
        if let Some(token) = &self.token {
            req = req.bearer_auth(token);
        }
        if let Some(body) = body {
            req = req.json(body);
        }
        let res = req.send().await?;
        Ok(res.json().await?)
    }

"#,
    );

    for route in routes {
        let fn_name = to_snake_case(&route.export_name);
        let method = route.method.to_uppercase();
        let path = &route.path;

        let params: Vec<&str> = path
            .split('/')
            .filter_map(|s| s.strip_prefix(':'))
            .collect();
        let has_body = matches!(method.as_str(), "POST" | "PUT" | "PATCH");

        let mut args = Vec::new();
        for param in &params {
            args.push(format!("{param}: &str"));
        }
        if has_body {
            args.push("body: &Value".to_string());
        }
        let args_str = if args.is_empty() {
            "&self".to_string()
        } else {
            format!("&self, {}", args.join(", "))
        };

        // Build path with replacements
        let mut path_expr = format!("\"{path}\"");
        for param in &params {
            path_expr = format!("{path_expr}.replace(\":{param}\", {param})");
        }

        let body_arg = if has_body { "Some(body)" } else { "None" };

        code.push_str(&format!(
            "    pub async fn {fn_name}({args_str}) -> Result<Value> {{\n        let path = {path_expr};\n        self.request(\"{method}\", &path, {body_arg}).await\n    }}\n\n"
        ));
    }

    code.push_str("}\n");
    code
}

fn generate_postman_collection(routes: &[RouteInfo]) -> serde_json::Value {
    let items: Vec<serde_json::Value> = routes
        .iter()
        .map(|route| {
            let url_parts: Vec<&str> = route.path.trim_start_matches('/').split('/').collect();
            serde_json::json!({
                "name": route.export_name,
                "request": {
                    "method": route.method,
                    "url": {
                        "raw": format!("{{{{baseUrl}}}}{}", route.path),
                        "host": ["{{baseUrl}}"],
                        "path": url_parts,
                    },
                    "header": if route.auth {
                        vec![serde_json::json!({"key": "Authorization", "value": "Bearer {{token}}"})]
                    } else {
                        vec![]
                    },
                }
            })
        })
        .collect();

    serde_json::json!({
        "info": {
            "name": "Cooper API",
            "schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json"
        },
        "variable": [
            { "key": "baseUrl", "value": "http://localhost:4000" },
            { "key": "token", "value": "" }
        ],
        "item": items
    })
}

fn to_snake_case(s: &str) -> String {
    let mut result = String::new();
    for (i, ch) in s.chars().enumerate() {
        if ch.is_uppercase() {
            if i > 0 {
                result.push('_');
            }
            result.push(ch.to_lowercase().next().unwrap());
        } else {
            result.push(ch);
        }
    }
    result
}
