use crate::analyzer::ProjectAnalysis;

/// Generate a COOPER.md file describing the service graph.
pub fn generate(analysis: &ProjectAnalysis, project_name: &str) -> String {
    let mut md = String::new();

    md.push_str(&format!("# {project_name}\n\n"));
    md.push_str("_Auto-generated by Cooper. Do not edit — regenerate with `cooper build`._\n\n");

    // Services overview
    md.push_str("## Services\n\n");

    // Group routes by service
    let mut services: std::collections::HashMap<String, Vec<&crate::analyzer::RouteInfo>> =
        std::collections::HashMap::new();
    for route in &analysis.routes {
        let parts: Vec<&str> = route.source_file.split('/').collect();
        let svc = if parts.len() >= 2 && parts[0] == "services" {
            parts[1].to_string()
        } else {
            "root".to_string()
        };
        services.entry(svc).or_default().push(route);
    }

    for (service, routes) in &services {
        md.push_str(&format!("### {service}\n\n"));
        md.push_str("| Method | Path | Handler | Auth |\n");
        md.push_str("|--------|------|---------|------|\n");
        for route in routes {
            let auth = if route.auth { "yes" } else { "" };
            md.push_str(&format!(
                "| `{}` | `{}` | `{}` | {} |\n",
                route.method, route.path, route.export_name, auth
            ));
        }
        md.push('\n');
    }

    // Databases
    if !analysis.databases.is_empty() {
        md.push_str("## Databases\n\n");
        md.push_str("| Name | Engine | Migrations |\n");
        md.push_str("|------|--------|------------|\n");
        for db in &analysis.databases {
            md.push_str(&format!(
                "| `{}` | {} | {} |\n",
                db.name,
                db.engine,
                db.migrations.as_deref().unwrap_or("-")
            ));
        }
        md.push('\n');
    }

    // Topics
    if !analysis.topics.is_empty() {
        md.push_str("## Pub/Sub Topics\n\n");
        for topic in &analysis.topics {
            md.push_str(&format!("- `{}`\n", topic.name));
        }
        md.push('\n');
    }

    // Queues
    if !analysis.queues.is_empty() {
        md.push_str("## Queues\n\n");
        for queue in &analysis.queues {
            md.push_str(&format!("- `{}`\n", queue.name));
        }
        md.push('\n');
    }

    // Crons
    if !analysis.crons.is_empty() {
        md.push_str("## Cron Jobs\n\n");
        md.push_str("| Name | Schedule |\n");
        md.push_str("|------|----------|\n");
        for cron in &analysis.crons {
            md.push_str(&format!("| `{}` | `{}` |\n", cron.name, cron.schedule));
        }
        md.push('\n');
    }

    // Pages
    if !analysis.pages.is_empty() {
        md.push_str("## Pages\n\n");
        for page in &analysis.pages {
            md.push_str(&format!("- `{}` → `{}`\n", page.route, page.source_file));
        }
        md.push('\n');
    }

    // Architecture diagram (ASCII)
    md.push_str("## Architecture\n\n");
    md.push_str("```\n");
    md.push_str("  Client\n");
    md.push_str("    │\n");
    md.push_str("    ▼\n");
    md.push_str("  ┌─────────────────────────┐\n");
    md.push_str("  │   Cooper Runtime (Rust)  │\n");
    md.push_str("  │   Hyper + Tokio + Axum   │\n");
    md.push_str("  └────────┬────────────────┘\n");
    md.push_str("           │\n");

    if !services.is_empty() {
        md.push_str("    ┌──────┼──────┐\n");
        let svc_names: Vec<String> = services.keys().cloned().collect();
        for (i, name) in svc_names.iter().enumerate() {
            if i == 0 {
                md.push_str(&format!("    ▼      ▼      ▼\n"));
                md.push_str(&format!("  [{}]", name));
                for n in svc_names.iter().skip(1).take(2) {
                    md.push_str(&format!("  [{}]", n));
                }
                md.push('\n');
                break;
            }
        }
    }

    md.push_str("           │\n");
    md.push_str("    ┌──────┼──────┐\n");
    md.push_str("    ▼      ▼      ▼\n");

    let mut infra = Vec::new();
    if !analysis.databases.is_empty() {
        infra.push("Postgres");
    }
    if !analysis.topics.is_empty() || !analysis.queues.is_empty() {
        infra.push("NATS");
    }
    infra.push("Valkey");

    md.push_str(&format!("  {}\n", infra.join("  ")));
    md.push_str("```\n");

    md
}
